### ISSUE TITLE
CTRL+q to close or option to remap

### ISSUE THREAD

**Issue by bashruleseverythingaroundme** [jtheoof/swappy#102]
Hello,

first thing first, thank you so much for this amazing app, I use it daily and it's a time saver!

If I can suggest a very small addition would be allowing to close the app using CTRL+q or an option to remap the keys in the config.

I use sway and CTRL+q is the keybind that closes app almost everywhere so I keep hitting it in swappy but nothing happens, then I remember it's CTRL+w.

A very minor annoyance for an amazing app, thanks again and keep up the great work!

**Comment by jtheoof** [comment]
Hi @bashruleseverythingaroundme your `CTRL+q` sway keybinding should definitely exit swappy. (It does on my machine). This + `Escape` or `q` should work too. 

I think we should keep options for things that really add value, since the closing of windows belongs to the window manager I'd leave it at that :smile: 

Please check that your sway keybinding is properly configured and come back here if the issue persists.
