### ISSUE TITLE
[Feature Request] Solid rectangular box

### ISSUE THREAD

**Issue by CodedBinary** [jtheoof/swappy#120]
It would be nice to be able to draw a solid rectangular box. For example, redacting text with blur is insecure, so being able to use a solid box would make it much easier to quickly send images with sensitive content.

**Comment by apiraino** [comment]
@CodedBinary just out of curiosity, what is insecure about this blur?
![grafik](https://user-images.githubusercontent.com/6098822/141663651-578d9ab6-9236-43fd-b911-f863a4d6d9f0.png)

If you're worried about an attack that can reverse the blur, one workaround could be to give more passes with blur and make the text completely unrecoverable

**Comment by CodedBinary** [comment]
@apiraino Yes, I am worried about attacks that can reverse the blur. How many passes are required to make the text unrecoverable? It isn't really clear to me when this will have occurred, because even if to the human eye something looks like a grey mush, a computer might see there is only one text string that could have resulted in that particular grey mush. And as a human I'm not sure when this is no longer possible.

I typically just use the pen on the highest width setting to draw over the text, but this is obviously messy, and doesn't leave behind nice straight boxes like the rectangle and blur tools do.

Is this kind of concern out of scope?

**Comment by apiraino** [comment]
If I had to blur _really_ sensitive data, I wouldn't use swappy in the first place, simply because it does not make any claims about being a privacy tool :)

I am not familiar with tecniques to reverse blurs but the implementation in swappy is [here](https://github.com/jtheoof/swappy/blob/0d383f690b99026c340eab1efa590c48d54e7368/src/render.c#L18) (with a handy link to the original Cairo implementation). If you're curious you can investigate how resistant to attacks could be (an interesting topic on its own)
