### ISSUE TITLE
Auto-add border to screenshot

### ISSUE THREAD

**Issue by Xeyk** [jtheoof/swappy#186]
Hello. I send out a large amount of screenshots through email for troubleshooting steps. I like to add borders to the images to create a nice, clean look in email. 

Here's an example of what a screenshot with a border would look like:
![image](https://github.com/user-attachments/assets/918b60c8-0011-4b1f-92e1-18bbc2c7f59d)

This is a feature in the Windows software SnagIt that I miss dearly. Would it be possible to implement a border feature for Swappy? I currently draw my own borders with the rectangle shape, but that isn't the most accurate and is also time consuming.

**Comment by kadamski** [comment]
That is a very specific usecase and I don't think there will be many users of this functionality. And then not everybody would like the same kind of border which would only complicate things. I don't think it makes much sense to implement this in swappy since you can actually easily do it externally.
You are currently already using a pipeline with slurp and grim to send the image to swappy so you can also add one additional step that would paint the border for you. You can do that for example with imagemagick like this:
```
grim -g "$(slurp)" - | convert -frame 5x5+0+5 - - | swappy -f -
```
or
```
grim -g "$(slurp)" - | convert -border 5 -bordercolor darkgray - - | swappy -f -
```
This will add a 5 pixel wide frame around the screenshot grabbed by grim before sending it to swappy. If you like to change the border appearance you can configure your imagemagick arguments accordingly. See (imagemagick docs)[https://usage.imagemagick.org/crop/#border] for more details.

**Comment by Xeyk** [comment]
Thank you for providing a reply and also a very reasonable alternative! I'll implement that instead.
