### ISSUE TITLE
Allow disable notifications

### ISSUE THREAD

**Issue by JoyHusky** [jtheoof/swappy#58]
Can you please add disable notify option in config?

**Comment by maximbaz** [comment]
If you are compiling `swappy` for yourself, you can use `libnotify` option [to disable it](https://github.com/jtheoof/swappy/blob/f3a4ae900976255ea2b49c58fe5dac1829102535/meson_options.txt#L2), but I completely agree, it would be much more preferable to be able to configure this in user config, it's especially unfair with distro packages, when package maintainer must decide for the entire distro whether the tool will be compiled with or without notifications.

**Comment by jtheoof** [comment]
Yes I'm debating if I shouldn't get rid of the notifications completely. They don't add that much to the tool besides bringing instant feedback. I don't think it's worth pulling a 3rd party lib, just for that.

**Comment by maximbaz** [comment]
Have you decided something about notifications, getting rid of them perhaps? 🙂 

Now that you are preparing a new release, I was thinking to bring swappy to `[community]` repo at the same time, but the problem is that I would have to decide in compile time for everyone else whether they should have notifications or not - which is not very nice. And by default Arch enables all options, meaning that notifications should be enabled for everyone, but selfish me actually _doesn't_ want notifications 😅 

Ideally we either always pull in the `libnotify` dependency but allow disabling notifications via config, or just get rid of them for now. While people have to configure this in compile-time, I think it will bring more harm than good moving swappy from AUR to community...

**Comment by jtheoof** [comment]
You're right, let's get rid of the `libnotify` for the time being. I don't think a snapshot editing tool should depend on a notification library anyway. I'll monitor if there are complaints after release, will try to find a more elegant solution if that happens.

**Comment by lokesh-krishna** [comment]
I know notifications don't add anything of value to the experience when using a dedicated tool but since I used to use a script to take screenshots originally, the notifications served as feedback for whether things went as planned and now I'm so used to that that not getting a notification makes me think the screenshot wasn't taken.

For those interested in still having a notification, is there a way to get it back? Maybe add it in as an optional dependency?

**Comment by maximbaz** [comment]
Have you considered a simple wrapper script?

```sh
#!/bin/sh

grim -g "$(slurp)" - | swappy -f -
notify-send "Screenshot was taken!"
```

**Comment by lokesh-krishna** [comment]
That would be perfect! However, would that trigger the notification upon pressing the keybind or upon selecting to save the screenshot?

**Comment by maximbaz** [comment]
The snippet above (I've just slightly updated it) would only show notification if nothing crashed, so you can trust that at least swappy did all you asked it to do and didn't exit unexpectedly.

If you want notifications on save, something like this would probably work (so another script entirely):

```sh
#!/bin/sh

set -e

while true; do
    inotifywait -q -e create /tmp/screenshots/
    notify-send "Screenshot saved"
done
```

If you want to monitor clipboard, maybe something like this would be enough? 

```sh
#!/bin/bash

grim -g "$(slurp)" - | swappy -f -
notify-send "Screenshot was taken!"
[[ $(wl-paste -l) == "image/png" ]] && notify-send "and was even copied!"
```

All of these are just ideas, so don't take it as an absolute "no this must never be done in the app itself", but I'm just trying to inspire you, and if all you really need is a simple notification to make sure that swappy didn't crash, it might be enough...

**Comment by lokesh-krishna** [comment]
This looks like all I need. Thank you so much!

**Comment by markstos** [comment]
I came to say it would be it would nice to have some feedback when the "save"  button is pressed. Now nothing appears to happen, which seems broken. An external  dependency is not required-- a simple in-app modal that briefly appears would work as well: 

_Screenshot saved to ~/Desktop/swappy-2021-03-01.png_

I attempted to see if I could create a DIY save notification:

      grimshot save area - | swappy -f - | notify-send "test"

But the notification is sent as soon as Swappy opens the file instead of when Swappy saves it.

**Comment by Isti115** [comment]
After installing swappy on another machine I kept thinking that I have somehow misconfigured mako and that's why the notifications are not shown. :upside_down_face: I agree, that it would be nice to at least have an option for feedback, especially since I'm often using shortcuts (Ctrl+C to copy, Ctrl+S to save), which currently give zero feedback of their execution. I understand that you don't think that depending on libnotify is a good idea for a screenshot tool and actually agree with this, but a simple status message at the bottom of the window or something like that, which can easily bee integrated would be much appreciated! (As is already all the work you put into this amazing tool! :+1:)
Personally I think that a modal could be potentially too intrusive, but that's just my two cents.

**Comment by boredland** [comment]
Would it be an option for swappy to output the file name on exit so we could just pipe it to sth along the line of `xargs notify-send`?

**Comment by boredland** [comment]
> I'll monitor if there are complaints after release

Just to make that clear: I really don't like that we now have to have two workarounds (clipboard-check & inotify for the files) in place to get "any" visible confirmation of swappy doing "anything".
