### ISSUE TITLE
Feature request: Delete button

### ISSUE THREAD

**Issue by Hubro** [jtheoof/swappy#88]
I often want to take a screenshot, copy it in somewhere then immediately delete it from disk to keep things tidy. When using Swappy as my "screenshot GUI", my usual workflow currently looks like this:

1. Press screenshot key on the keyboard, which launches `grim` and opens the resulting file in Swappy
2. Draw some arrows, blur some sensitive information
3. Press ctrl+c
4. Paste image into chat or email
5. Go back to Swappy and close it
6. Open file manager
7. Browse to screenshot directory
8. Delete screenshot

I think it would be nice to add a "Delete" button when Swappy is launched with the `-f` argument pointing to a file. The button could have a trash can icon and be placed to the left of the copy button. When pressed, Swappy would exit, delete the file and display a notification saying "Screenshot deleted".

As an extra convenience, it could have a keyboard shortcut bound to the delete key by default.

When the image is passed via STDIN, the button would be hidden or greyed out.

This would simplify the previous workflow a lot:

1. Press screenshot key on keyboard, which launches `grim` and opens the resulting file in Swappy
2. Draw some arrows, blur some sensitive information
3. Press ctrl+c
4. Paste image into chat or email
5. Go back to Swappy and press the delete key

**Comment by jtheoof** [comment]
Most of the things you describe is already handled by swappy. You can:

1. Output grim to sdout
2. Pipe in swappy as stdin
3. Do your edit
4. Ctrl+C
5. Escape

You now have a valid swappy buffer in your clipboard. No need to remove anything.

Overall, swappy shouldn't delete file from users filesystem. What it should do is cleanup after itself when using `-f -` option and this was handled in #80 .

For the notification, they were removed in my patch yesterday. See #58 details for the reason behind this.

Overall the idea is to keep the tool as simple as possible and I think your proposal goes against it.

**Comment by WhyNotHugo** [comment]
Hi!

I [long ago] wrote `shotman` for taking screenshots, but, honestly, `swappy` is far more feature-rich and does does 99% of all the extra things I'd want, and I'd love to drop my own tool and move over to swappy.

However, the lack of a delete button is a hard dealbreaker for me.

I really dislike the idea of "only keep in memory by default". In case of failure, or accidentally closing `swappy`, the data is lost forever. The idea of "data is discarded by default, only save explicitly" seems too fragile for me.

The opposite approach: save by default, and require explicit deletion would seem safer and reliable in almost any scenario. I'd love to do something like:

    swappy -f $(grimshot save output)

This approach also separates roles clearly: `grimshot` takes a screenshot, `swappy` shows a UI to operate on it.

However, I'd need a hotkey to delete the file if I chose to, especially since I'm already looking at a UI. This model is honestly, just inspired by what iOS does (my intention with `shotman` was to follow that approach, but I've never had the time for it).

Can this feature be revisited?
